.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. wentuno_qt test_wentuno_qt
clean: FORCE
	$(MAKE) -C .. wentuno_qt_clean test_wentuno_qt_clean
check: FORCE
	$(MAKE) -C .. test_wentuno_qt_check
wentuno-qt wentuno-qt.exe: FORCE
	 $(MAKE) -C .. wentuno_qt
apk: FORCE
	$(MAKE) -C .. wentuno_qt_apk
